export interface PropertyCommissionDeal {
  id: string;
  landId: string;
  customerName: string;
  location: string;
  imageUrl: string;
  saleValue: string;
  earnedAmount: string;
  pendingAmount: string;
  status: 'Settled' | 'Pending';
}

export interface AgentCommission {
  id: string;
  name: string;
  agentId: string;
  avatarUrl: string;
  role?: string;
  region: string;
  district?: string;
  mandal?: string;
  areaOrDistrict: string;
  areaLabel: 'Area' | 'District';
  landId: string;
  date: string;
  amount: number;
  formattedAmount: string;
  status: 'Paid' | 'Pending';
  phone?: string;
  email?: string;
  bankAccount?: string;
  ifscCode?: string;
  plotSize?: string;
  commissionRate?: string;
  transactionRef?: string;
  payoutDate?: string;
  isTopPerformer?: boolean;
  isVerified?: boolean;
  deals?: PropertyCommissionDeal[];
}

export const samplePropertyDeals: PropertyCommissionDeal[] = [
  {
    id: 'prop-1',
    landId: 'GLC SOS 01',
    customerName: 'Venkatesh Rao',
    location: 'Mahabubnagar, Jadcherla',
    imageUrl: '/assets/property-1.png',
    saleValue: '₹15,00,000',
    earnedAmount: '₹75,000',
    pendingAmount: '₹0',
    status: 'Settled',
  },
  {
    id: 'prop-2',
    landId: 'GLC SOS 01',
    customerName: 'Venkatesh Rao',
    location: 'Mahabubnagar, Jadcherla',
    imageUrl: '/assets/property-2.png',
    saleValue: '₹15,00,000',
    earnedAmount: '₹34,000',
    pendingAmount: '₹23,000',
    status: 'Pending',
  },
  {
    id: 'prop-3',
    landId: 'GLC SOS 01',
    customerName: 'Venkatesh Rao',
    location: 'Mahabubnagar, Jadcherla',
    imageUrl: '/assets/property-3.png',
    saleValue: '₹15,00,000',
    earnedAmount: '₹75,000',
    pendingAmount: '₹0',
    status: 'Settled',
  },
  {
    id: 'prop-4',
    landId: 'GLC SOS 01',
    customerName: 'Venkatesh Rao',
    location: 'Mahabubnagar, Jadcherla',
    imageUrl: '/assets/property-4.png',
    saleValue: '₹15,00,000',
    earnedAmount: '₹75,000',
    pendingAmount: '₹0',
    status: 'Settled',
  },
];

export const agentCommissions: AgentCommission[] = [
  {
    id: 'comm-1',
    name: 'Ravi Kumar',
    agentId: 'ID-8327492',
    avatarUrl: '/assets/agent-1.png',
    role: 'Senior Sales Agent',
    region: 'Mahabubnagar',
    district: 'Mahabubnagar',
    mandal: 'Jadcherla',
    areaOrDistrict: 'Jadcherla',
    areaLabel: 'Area',
    landId: 'GLC SOS 01',
    date: '29 May 2025',
    amount: 75000,
    formattedAmount: '₹75,000',
    status: 'Paid',
    phone: '+91 98490 23145',
    email: 'ravi.kumar@glc-agents.in',
    bankAccount: 'HDFC •••• 4120',
    ifscCode: 'HDFC0001824',
    plotSize: '2.5 Acres',
    commissionRate: '2.5% on Land Deal',
    transactionRef: 'TXN-9824719284',
    payoutDate: '29 May 2025, 03:45 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-2',
    name: 'Kiran Shetty',
    agentId: 'ID-8327492',
    avatarUrl: '/assets/agent-2.png',
    role: 'Field Acquisition Partner',
    region: 'Vikarabad',
    district: 'Vikarabad',
    mandal: 'Pargi',
    areaOrDistrict: 'Pargi',
    areaLabel: 'District',
    landId: 'GLC SOS 56',
    date: '29 May 2025',
    amount: 45000,
    formattedAmount: '₹45,000',
    status: 'Pending',
    phone: '+91 98481 99201',
    email: 'kiran.shetty@glc-agents.in',
    bankAccount: 'ICICI •••• 8831',
    ifscCode: 'ICIC0000491',
    plotSize: '1.8 Acres',
    commissionRate: '2.0% on Land Deal',
    transactionRef: 'TXN-PENDING-041',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals.map((d, i) => ({
      ...d,
      id: `prop-kiran-${i}`,
      landId: 'GLC SOS 56',
      location: 'Vikarabad, Pargi',
    })),
  },
  {
    id: 'comm-3',
    name: 'Arjun',
    agentId: 'ID-8327492',
    avatarUrl: '/assets/agent-3.png',
    role: 'Senior Sales Agent',
    region: 'Mahabubnagar',
    district: 'Mahabubnagar',
    mandal: 'Jadcherla',
    areaOrDistrict: 'Patancheru',
    areaLabel: 'District',
    landId: 'GLC SOS 321',
    date: '29 May 2025',
    amount: 53000,
    formattedAmount: '₹53,000',
    status: 'Pending',
    phone: '+91 98765 43210',
    email: 'arjun.reddy@glc-agents.in',
    bankAccount: 'SBI •••• 9924',
    ifscCode: 'SBIN0008432',
    plotSize: '2.0 Acres',
    commissionRate: '2.2% on Land Deal',
    transactionRef: 'TXN-PENDING-089',
    payoutDate: 'Pending Authorization',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-4',
    name: 'Meghana Patel',
    agentId: 'ID-8327492',
    avatarUrl: '/assets/agent-4.png',
    role: 'Executive Land Specialist',
    region: 'Hyderabad',
    district: 'Hyderabad',
    mandal: 'Patancheru',
    areaOrDistrict: 'Patancheru',
    areaLabel: 'District',
    landId: 'GLC SOS 01',
    date: '29 May 2025',
    amount: 65000,
    formattedAmount: '₹65,000',
    status: 'Paid',
    phone: '+91 97012 33418',
    email: 'meghana.patel@glc-agents.in',
    bankAccount: 'Axis •••• 6612',
    ifscCode: 'UTIB0001021',
    plotSize: '3.0 Acres',
    commissionRate: '2.5% on Land Deal',
    transactionRef: 'TXN-8812947102',
    payoutDate: '29 May 2025, 05:12 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals.map((d, i) => ({
      ...d,
      id: `prop-meghana-${i}`,
      location: 'Hyderabad, Patancheru',
    })),
  },
  {
    id: 'comm-5',
    name: 'Venu Goud',
    agentId: 'ID-8327492',
    avatarUrl: '/assets/agent-5.png',
    role: 'Regional Deal Partner',
    region: 'Mahabubnagar',
    district: 'Mahabubnagar',
    mandal: 'Gachibowli',
    areaOrDistrict: 'Gachibowli',
    areaLabel: 'District',
    landId: 'GLC SOS 12',
    date: '29 May 2025',
    amount: 48000,
    formattedAmount: '₹48,000',
    status: 'Pending',
    phone: '+91 94401 77312',
    email: 'venu.goud@glc-agents.in',
    bankAccount: 'HDFC •••• 1928',
    ifscCode: 'HDFC0001824',
    plotSize: '1.5 Acres',
    commissionRate: '2.0% on Land Deal',
    transactionRef: 'TXN-PENDING-112',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals.map((d, i) => ({
      ...d,
      id: `prop-venu-${i}`,
      landId: 'GLC SOS 12',
    })),
  },
  {
    id: 'comm-6',
    name: 'Suresh Babu',
    agentId: 'ID-8327492',
    avatarUrl: '/assets/agent-6.png',
    role: 'Senior Sales Agent',
    region: 'Ranga Reddy',
    district: 'Ranga Reddy',
    mandal: 'Gachibowli',
    areaOrDistrict: 'Gachibowli',
    areaLabel: 'District',
    landId: 'GLC SOS 23',
    date: '29 May 2025',
    amount: 52000,
    formattedAmount: '₹52,000',
    status: 'Paid',
    phone: '+91 98852 44109',
    email: 'suresh.babu@glc-agents.in',
    bankAccount: 'Kotak •••• 5543',
    ifscCode: 'KKBK0000213',
    plotSize: '2.2 Acres',
    commissionRate: '2.4% on Land Deal',
    transactionRef: 'TXN-7731092481',
    payoutDate: '29 May 2025, 01:20 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals.map((d, i) => ({
      ...d,
      id: `prop-suresh-${i}`,
      landId: 'GLC SOS 23',
      location: 'Ranga Reddy, Gachibowli',
    })),
  },
  {
    id: 'comm-7',
    name: 'Priya Sharma',
    agentId: 'ID-8327493',
    avatarUrl: '/assets/avatar.png',
    role: 'Senior Acquisition Agent',
    region: 'Medak',
    district: 'Medak',
    mandal: 'Sangareddy',
    areaOrDistrict: 'Sangareddy',
    areaLabel: 'District',
    landId: 'GLC SOS 44',
    date: '28 May 2025',
    amount: 82000,
    formattedAmount: '₹82,000',
    status: 'Paid',
    phone: '+91 98491 55210',
    email: 'priya.sharma@glc-agents.in',
    bankAccount: 'HDFC •••• 5519',
    ifscCode: 'HDFC0001824',
    plotSize: '3.2 Acres',
    commissionRate: '2.5% on Land Deal',
    transactionRef: 'TXN-9912048123',
    payoutDate: '28 May 2025, 04:10 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-8',
    name: 'Rajesh Verma',
    agentId: 'ID-8327494',
    avatarUrl: '/assets/lead-1.png',
    role: 'Regional Deal Partner',
    region: 'Nalgonda',
    district: 'Nalgonda',
    mandal: 'Miryalaguda',
    areaOrDistrict: 'Miryalaguda',
    areaLabel: 'District',
    landId: 'GLC SOS 78',
    date: '28 May 2025',
    amount: 38000,
    formattedAmount: '₹38,000',
    status: 'Pending',
    phone: '+91 97002 88412',
    email: 'rajesh.verma@glc-agents.in',
    bankAccount: 'SBI •••• 3310',
    ifscCode: 'SBIN0001204',
    plotSize: '1.4 Acres',
    commissionRate: '2.0% on Land Deal',
    transactionRef: 'TXN-PENDING-142',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-9',
    name: 'Vikram Malhotra',
    agentId: 'ID-8327495',
    avatarUrl: '/assets/lead-2.png',
    role: 'Executive Land Specialist',
    region: 'Warangal',
    district: 'Warangal',
    mandal: 'Kazipet',
    areaOrDistrict: 'Kazipet',
    areaLabel: 'District',
    landId: 'GLC SOS 92',
    date: '27 May 2025',
    amount: 95000,
    formattedAmount: '₹95,000',
    status: 'Paid',
    phone: '+91 99890 11490',
    email: 'vikram.m@glc-agents.in',
    bankAccount: 'ICICI •••• 7741',
    ifscCode: 'ICIC0000491',
    plotSize: '4.0 Acres',
    commissionRate: '2.8% on Land Deal',
    transactionRef: 'TXN-8823190412',
    payoutDate: '27 May 2025, 11:30 AM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-10',
    name: 'Sneha Reddy',
    agentId: 'ID-8327496',
    avatarUrl: '/assets/avatar_test1.png',
    role: 'Field Acquisition Partner',
    region: 'Nizamabad',
    district: 'Nizamabad',
    mandal: 'Armoor',
    areaOrDistrict: 'Armoor',
    areaLabel: 'District',
    landId: 'GLC SOS 105',
    date: '27 May 2025',
    amount: 62000,
    formattedAmount: '₹62,000',
    status: 'Pending',
    phone: '+91 98488 22391',
    email: 'sneha.reddy@glc-agents.in',
    bankAccount: 'Axis •••• 2219',
    ifscCode: 'UTIB0001021',
    plotSize: '2.5 Acres',
    commissionRate: '2.2% on Land Deal',
    transactionRef: 'TXN-PENDING-167',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-11',
    name: 'K. R. Karthik',
    agentId: 'ID-8327497',
    avatarUrl: '/assets/avatar_test2.png',
    role: 'Senior Sales Agent',
    region: 'Khammam',
    district: 'Khammam',
    mandal: 'Kothagudem',
    areaOrDistrict: 'Kothagudem',
    areaLabel: 'District',
    landId: 'GLC SOS 118',
    date: '26 May 2025',
    amount: 71000,
    formattedAmount: '₹71,000',
    status: 'Paid',
    phone: '+91 97033 77124',
    email: 'karthik.kr@glc-agents.in',
    bankAccount: 'Kotak •••• 4492',
    ifscCode: 'KKBK0000213',
    plotSize: '2.8 Acres',
    commissionRate: '2.4% on Land Deal',
    transactionRef: 'TXN-7712093841',
    payoutDate: '26 May 2025, 02:45 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-12',
    name: 'Harish Patel',
    agentId: 'ID-8327498',
    avatarUrl: '/assets/avatar_test3.png',
    role: 'Field Deal Associate',
    region: 'Karimnagar',
    district: 'Karimnagar',
    mandal: 'Jagtial',
    areaOrDistrict: 'Jagtial',
    areaLabel: 'District',
    landId: 'GLC SOS 134',
    date: '26 May 2025',
    amount: 44000,
    formattedAmount: '₹44,000',
    status: 'Pending',
    phone: '+91 99081 44210',
    email: 'harish.patel@glc-agents.in',
    bankAccount: 'SBI •••• 8821',
    ifscCode: 'SBIN0008432',
    plotSize: '1.6 Acres',
    commissionRate: '2.0% on Land Deal',
    transactionRef: 'TXN-PENDING-189',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-13',
    name: 'Divya Nair',
    agentId: 'ID-8327499',
    avatarUrl: '/assets/agent-1.png',
    role: 'Senior Sales Agent',
    region: 'Hyderabad',
    district: 'Hyderabad',
    mandal: 'Shamshabad',
    areaOrDistrict: 'Shamshabad',
    areaLabel: 'Area',
    landId: 'GLC SOS 142',
    date: '25 May 2025',
    amount: 88000,
    formattedAmount: '₹88,000',
    status: 'Paid',
    phone: '+91 98492 33120',
    email: 'divya.nair@glc-agents.in',
    bankAccount: 'HDFC •••• 9912',
    ifscCode: 'HDFC0001824',
    plotSize: '3.5 Acres',
    commissionRate: '2.6% on Land Deal',
    transactionRef: 'TXN-6612984102',
    payoutDate: '25 May 2025, 05:00 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-14',
    name: 'Sandeep Varma',
    agentId: 'ID-8327500',
    avatarUrl: '/assets/agent-2.png',
    role: 'Executive Land Specialist',
    region: 'Mahabubnagar',
    district: 'Mahabubnagar',
    mandal: 'Shadnagar',
    areaOrDistrict: 'Shadnagar',
    areaLabel: 'Area',
    landId: 'GLC SOS 155',
    date: '25 May 2025',
    amount: 56000,
    formattedAmount: '₹56,000',
    status: 'Pending',
    phone: '+91 98480 66491',
    email: 'sandeep.v@glc-agents.in',
    bankAccount: 'ICICI •••• 4421',
    ifscCode: 'ICIC0000491',
    plotSize: '2.0 Acres',
    commissionRate: '2.1% on Land Deal',
    transactionRef: 'TXN-PENDING-203',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-15',
    name: 'Anusha Reddy',
    agentId: 'ID-8327501',
    avatarUrl: '/assets/agent-3.png',
    role: 'Field Acquisition Partner',
    region: 'Ranga Reddy',
    district: 'Ranga Reddy',
    mandal: 'Maheshwaram',
    areaOrDistrict: 'Maheshwaram',
    areaLabel: 'Area',
    landId: 'GLC SOS 168',
    date: '24 May 2025',
    amount: 79000,
    formattedAmount: '₹79,000',
    status: 'Paid',
    phone: '+91 97011 88320',
    email: 'anusha.r@glc-agents.in',
    bankAccount: 'Axis •••• 1198',
    ifscCode: 'UTIB0001021',
    plotSize: '3.0 Acres',
    commissionRate: '2.5% on Land Deal',
    transactionRef: 'TXN-5510293841',
    payoutDate: '24 May 2025, 03:15 PM',
    isTopPerformer: true,
    isVerified: true,
    deals: samplePropertyDeals,
  },
  {
    id: 'comm-16',
    name: 'Manoj Joshi',
    agentId: 'ID-8327502',
    avatarUrl: '/assets/agent-4.png',
    role: 'Regional Deal Associate',
    region: 'Vikarabad',
    district: 'Vikarabad',
    mandal: 'Tandur',
    areaOrDistrict: 'Tandur',
    areaLabel: 'District',
    landId: 'GLC SOS 180',
    date: '24 May 2025',
    amount: 47000,
    formattedAmount: '₹47,000',
    status: 'Pending',
    phone: '+91 99881 22940',
    email: 'manoj.joshi@glc-agents.in',
    bankAccount: 'Kotak •••• 7721',
    ifscCode: 'KKBK0000213',
    plotSize: '1.8 Acres',
    commissionRate: '2.0% on Land Deal',
    transactionRef: 'TXN-PENDING-215',
    payoutDate: 'Pending Authorization',
    isTopPerformer: false,
    isVerified: true,
    deals: samplePropertyDeals,
  },
];
