export interface CreditTransaction {
  id: string;
  date: string;
  landId: string;
  type: 'Credit Allocation' | 'Credit Consumption' | 'Cash Redemption';
  credits: number;
  cashEquivalent: string;
  status: 'Completed' | 'Pending' | 'Authorized';
}

export type CreditActivityCategory =
  | 'Land Based Credits'
  | 'Referral Credits'
  | 'Buyer Lead Credits'
  | 'Credit Redemptions';

export interface LandCreditActivity {
  id: string;
  landId: string;
  category: CreditActivityCategory;
  creditType: string;
  credits: number;
  earnedOn: string;
  cashEarned: string;
}

export const sampleLandCreditActivities: LandCreditActivity[] = [
  {
    id: 'act-1',
    landId: 'GLC SOS234',
    category: 'Land Based Credits',
    creditType: 'Initial Land Sourcing',
    credits: 10,
    earnedOn: '24 JUNE 2026',
    cashEarned: '20,000',
  },
  {
    id: 'act-2',
    landId: 'GLC SOS234',
    category: 'Land Based Credits',
    creditType: 'Initial Land Sourcing',
    credits: 30,
    earnedOn: '24 JUNE 2026',
    cashEarned: '20,000',
  },
  {
    id: 'act-3',
    landId: 'GLC SOS234',
    category: 'Land Based Credits',
    creditType: 'Initial Land Sourcing',
    credits: 5,
    earnedOn: '24 JUNE 2026',
    cashEarned: '20,000',
  },
  {
    id: 'act-4',
    landId: 'GLC KND108',
    category: 'Land Based Credits',
    creditType: 'Boundary Verification',
    credits: 15,
    earnedOn: '18 JUNE 2026',
    cashEarned: '30,000',
  },
  {
    id: 'act-5',
    landId: 'GLC WAL055',
    category: 'Referral Credits',
    creditType: 'Direct Peer Referral',
    credits: 25,
    earnedOn: '12 JUNE 2026',
    cashEarned: '50,000',
  },
  {
    id: 'act-6',
    landId: 'GLC TNK012',
    category: 'Buyer Lead Credits',
    creditType: 'Institutional Lead Conversion',
    credits: 40,
    earnedOn: '05 JUNE 2026',
    cashEarned: '80,000',
  },
  {
    id: 'act-7',
    landId: 'GLC VZG089',
    category: 'Credit Redemptions',
    creditType: 'Quarterly Settlement Payout',
    credits: 50,
    earnedOn: '01 JUNE 2026',
    cashEarned: '1,00,000',
  },
];

export interface AgentCredit {
  id: string;
  agentId: string;
  name: string;
  avatarUrl: string;
  location: string;
  region?: string;
  district?: string;
  mandal?: string;
  dateTime: string;
  totalCredits: number;
  creditsUsed: number;
  creditsRemaining: number;
  cashEarned: number;
  formattedCashEarned: string;
  phone: string;
  email: string;
  role: string;
  status: 'Authorized' | 'Pending';
  entityType?: 'Agent' | 'User';
  isTopPerformer?: boolean;
  isVerified?: boolean;
  activities?: LandCreditActivity[];
  recentTransactions?: CreditTransaction[];
}

export const agentCredits: AgentCredit[] = [
  {
    id: 'cred-1',
    agentId: 'ID-87348',
    name: 'Ram Varma',
    avatarUrl: '/assets/agent-1.png',
    location: 'WEST GODAVARI, TANUKU',
    dateTime: '6th Oct – 12:53 PM',
    totalCredits: 450,
    creditsUsed: 120,
    creditsRemaining: 330,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 98490 12845',
    email: 'ram.varma@greenlandcapital.in',
    role: 'Senior Field Partner',
    status: 'Authorized',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-101',
        date: '06 Oct 2026, 12:30 PM',
        landId: 'GLC SOS 01',
        type: 'Credit Consumption',
        credits: 40,
        cashEquivalent: '₹26,666.67',
        status: 'Completed',
      },
      {
        id: 'tx-102',
        date: '04 Oct 2026, 03:15 PM',
        landId: 'GLC KND 03',
        type: 'Credit Consumption',
        credits: 80,
        cashEquivalent: '₹53,333.33',
        status: 'Completed',
      },
      {
        id: 'tx-103',
        date: '01 Oct 2026, 10:00 AM',
        landId: 'GLC WAL 02',
        type: 'Credit Allocation',
        credits: 450,
        cashEquivalent: '₹3,00,000.00',
        status: 'Authorized',
      },
    ],
  },
  {
    id: 'cred-2',
    agentId: 'ID-34934',
    name: 'Ananya Rao',
    avatarUrl: '/assets/agent-2.png',
    location: 'EAST GODAVARI, KAKINADA',
    dateTime: '7th Oct – 10:15 AM',
    totalCredits: 450,
    creditsUsed: 120,
    creditsRemaining: 330,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 94402 78321',
    email: 'ananya.rao@greenlandcapital.in',
    role: 'Lead Farmland Specialist',
    status: 'Authorized',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-201',
        date: '07 Oct 2026, 09:45 AM',
        landId: 'GLC KAK 04',
        type: 'Credit Consumption',
        credits: 60,
        cashEquivalent: '₹40,000.00',
        status: 'Completed',
      },
      {
        id: 'tx-202',
        date: '05 Oct 2026, 02:20 PM',
        landId: 'GLC RJY 01',
        type: 'Credit Consumption',
        credits: 60,
        cashEquivalent: '₹40,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-3',
    agentId: 'ID-39443',
    name: 'K. Sastry',
    avatarUrl: '/assets/agent-3.png',
    location: 'VIZAG, ANAKAPALLE',
    dateTime: '8th Oct – 09:30 AM',
    totalCredits: 450,
    creditsUsed: 120,
    creditsRemaining: 330,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 97033 45612',
    email: 'k.sastry@greenlandcapital.in',
    role: 'Regional Deal Associate',
    status: 'Authorized',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-301',
        date: '08 Oct 2026, 09:10 AM',
        landId: 'GLC VZG 09',
        type: 'Credit Consumption',
        credits: 120,
        cashEquivalent: '₹80,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-4',
    agentId: 'ID-93842',
    name: 'Ram Varma',
    avatarUrl: '/assets/agent-4.png',
    location: 'WEST GODAVARI, TANUKU',
    dateTime: '6th Oct – 12:53 PM',
    totalCredits: 450,
    creditsUsed: 120,
    creditsRemaining: 330,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 98495 99120',
    email: 'r.varma.tanuku@greenlandcapital.in',
    role: 'Field Agent Partner',
    status: 'Pending',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-401',
        date: '06 Oct 2026, 11:00 AM',
        landId: 'GLC TNK 02',
        type: 'Credit Consumption',
        credits: 120,
        cashEquivalent: '₹80,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-5',
    agentId: 'ID-84539',
    name: 'Ananya Rao',
    avatarUrl: '/assets/agent-5.png',
    location: 'EAST GODAVARI, KAKINADA',
    dateTime: '7th Oct – 10:15 AM',
    totalCredits: 450,
    creditsUsed: 120,
    creditsRemaining: 330,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 98481 33452',
    email: 'ananya.kakinada@greenlandcapital.in',
    role: 'Senior Acquisition Agent',
    status: 'Authorized',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-501',
        date: '07 Oct 2026, 10:00 AM',
        landId: 'GLC KAK 07',
        type: 'Credit Consumption',
        credits: 120,
        cashEquivalent: '₹80,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-6',
    agentId: 'ID-87348',
    name: 'Ram Varma',
    avatarUrl: '/assets/agent-6.png',
    location: 'WEST GODAVARI, TANUKU',
    dateTime: '6th Oct – 12:53 PM',
    totalCredits: 450,
    creditsUsed: 120,
    creditsRemaining: 330,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 98662 55431',
    email: 'ram.varma2@greenlandcapital.in',
    role: 'Field Sales Associate',
    status: 'Pending',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-601',
        date: '06 Oct 2026, 12:45 PM',
        landId: 'GLC TNK 05',
        type: 'Credit Consumption',
        credits: 120,
        cashEquivalent: '₹80,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-7',
    agentId: 'ID-51209',
    name: 'Suresh Reddy',
    avatarUrl: '/assets/agent-1.png',
    location: 'GUNTUR, TENALI',
    dateTime: '9th Oct – 02:45 PM',
    totalCredits: 600,
    creditsUsed: 240,
    creditsRemaining: 360,
    cashEarned: 160000,
    formattedCashEarned: '₹1,60,000.00',
    phone: '+91 99882 11223',
    email: 'suresh.reddy@greenlandcapital.in',
    role: 'Senior Cluster Manager',
    status: 'Authorized',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-701',
        date: '09 Oct 2026, 02:00 PM',
        landId: 'GLC GNT 11',
        type: 'Credit Consumption',
        credits: 240,
        cashEquivalent: '₹1,60,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-8',
    agentId: 'ID-62391',
    name: 'Pooja Hegde',
    avatarUrl: '/assets/agent-2.png',
    location: 'KRISHNA, VIJAYAWADA',
    dateTime: '10th Oct – 11:20 AM',
    totalCredits: 500,
    creditsUsed: 150,
    creditsRemaining: 350,
    cashEarned: 100000,
    formattedCashEarned: '₹1,00,000.00',
    phone: '+91 91234 56789',
    email: 'pooja.h@greenlandcapital.in',
    role: 'Channel Partner Head',
    status: 'Authorized',
    entityType: 'Agent',
    recentTransactions: [
      {
        id: 'tx-801',
        date: '10 Oct 2026, 11:00 AM',
        landId: 'GLC VJA 03',
        type: 'Credit Consumption',
        credits: 150,
        cashEquivalent: '₹1,00,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'cred-9',
    agentId: 'ID-51029',
    name: 'S. K. Murthy',
    avatarUrl: '/assets/agent-3.png',
    location: 'GUNTUR, TENALI',
    dateTime: '11th Oct – 09:40 AM',
    totalCredits: 420,
    creditsUsed: 110,
    creditsRemaining: 310,
    cashEarned: 72000,
    formattedCashEarned: '₹72,000.00',
    phone: '+91 98492 88102',
    email: 'murthy.sk@greenlandcapital.in',
    role: 'Senior Field Partner',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-10',
    agentId: 'ID-78192',
    name: 'Kavita Pillai',
    avatarUrl: '/assets/agent-4.png',
    location: 'KURNOOL, NANDYAL',
    dateTime: '11th Oct – 02:15 PM',
    totalCredits: 480,
    creditsUsed: 130,
    creditsRemaining: 350,
    cashEarned: 88000,
    formattedCashEarned: '₹88,000.00',
    phone: '+91 97001 44321',
    email: 'kavita.p@greenlandcapital.in',
    role: 'Regional Deal Associate',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-11',
    agentId: 'ID-44021',
    name: 'Arvind Swamy',
    avatarUrl: '/assets/agent-5.png',
    location: 'NELLORE, KAVALI',
    dateTime: '12th Oct – 10:30 AM',
    totalCredits: 390,
    creditsUsed: 90,
    creditsRemaining: 300,
    cashEarned: 65000,
    formattedCashEarned: '₹65,000.00',
    phone: '+91 99890 22104',
    email: 'arvind.s@greenlandcapital.in',
    role: 'Lead Farmland Specialist',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-12',
    agentId: 'ID-92831',
    name: 'Meera Nambiar',
    avatarUrl: '/assets/agent-6.png',
    location: 'CHITTOOR, TIRUPATI',
    dateTime: '12th Oct – 04:00 PM',
    totalCredits: 520,
    creditsUsed: 140,
    creditsRemaining: 380,
    cashEarned: 95000,
    formattedCashEarned: '₹95,000.00',
    phone: '+91 98481 66320',
    email: 'meera.n@greenlandcapital.in',
    role: 'Senior Acquisition Agent',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-13',
    agentId: 'ID-63102',
    name: 'Naveen Reddy',
    avatarUrl: '/assets/lead-1.png',
    location: 'KADAPA, PRODDATUR',
    dateTime: '13th Oct – 11:10 AM',
    totalCredits: 460,
    creditsUsed: 125,
    creditsRemaining: 335,
    cashEarned: 82000,
    formattedCashEarned: '₹82,000.00',
    phone: '+91 97033 99120',
    email: 'naveen.r@greenlandcapital.in',
    role: 'Field Sales Associate',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-14',
    agentId: 'ID-81920',
    name: 'Sunita Chandran',
    avatarUrl: '/assets/lead-2.png',
    location: 'ANANTAPUR, HINDUPUR',
    dateTime: '13th Oct – 03:45 PM',
    totalCredits: 510,
    creditsUsed: 160,
    creditsRemaining: 350,
    cashEarned: 92000,
    formattedCashEarned: '₹92,000.00',
    phone: '+91 94411 33490',
    email: 'sunita.c@greenlandcapital.in',
    role: 'Territory Deal Manager',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-15',
    agentId: 'ID-37291',
    name: 'Praveen Kumar',
    avatarUrl: '/assets/avatar.png',
    location: 'PRAKASAM, ONGOLE',
    dateTime: '14th Oct – 09:20 AM',
    totalCredits: 440,
    creditsUsed: 115,
    creditsRemaining: 325,
    cashEarned: 78000,
    formattedCashEarned: '₹78,000.00',
    phone: '+91 99080 77123',
    email: 'praveen.k@greenlandcapital.in',
    role: 'Lead Farmland Specialist',
    status: 'Authorized',
    entityType: 'Agent',
  },
  {
    id: 'cred-16',
    agentId: 'ID-99201',
    name: 'Shilpa Rao',
    avatarUrl: '/assets/avatar_test1.png',
    location: 'SRIKAKULAM, PALASA',
    dateTime: '14th Oct – 01:50 PM',
    totalCredits: 475,
    creditsUsed: 135,
    creditsRemaining: 340,
    cashEarned: 86000,
    formattedCashEarned: '₹86,000.00',
    phone: '+91 98499 11024',
    email: 'shilpa.r@greenlandcapital.in',
    role: 'Senior Field Partner',
    status: 'Authorized',
    entityType: 'Agent',
  },
];

export const userCredits: AgentCredit[] = [
  {
    id: 'usr-1',
    agentId: 'USR-94812',
    name: 'Dr. Ramesh Gupta',
    avatarUrl: '/assets/avatar.png',
    location: 'HYDERABAD, GACHIBOWLI',
    dateTime: '5th Oct – 11:20 AM',
    totalCredits: 600,
    creditsUsed: 180,
    creditsRemaining: 420,
    cashEarned: 120000,
    formattedCashEarned: '₹1,20,000.00',
    phone: '+91 98480 77123',
    email: 'ramesh.gupta@medcorp.in',
    role: 'Platinum Farmland Investor',
    status: 'Authorized',
    entityType: 'User',
    recentTransactions: [
      {
        id: 'tx-u1',
        date: '05 Oct 2026, 11:00 AM',
        landId: 'GLC SOS 01',
        type: 'Credit Consumption',
        credits: 60,
        cashEquivalent: '₹40,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'usr-2',
    agentId: 'USR-38194',
    name: 'Sunita Verma',
    avatarUrl: '/assets/avatar_test1.png',
    location: 'BENGALURU, WHITEFIELD',
    dateTime: '6th Oct – 03:15 PM',
    totalCredits: 400,
    creditsUsed: 100,
    creditsRemaining: 300,
    cashEarned: 75000,
    formattedCashEarned: '₹75,000.00',
    phone: '+91 99001 23456',
    email: 'sunita.v@techventures.io',
    role: 'Growth Plan Subscriber',
    status: 'Authorized',
    entityType: 'User',
    recentTransactions: [
      {
        id: 'tx-u2',
        date: '06 Oct 2026, 03:00 PM',
        landId: 'GLC KND 03',
        type: 'Credit Consumption',
        credits: 100,
        cashEquivalent: '₹75,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'usr-3',
    agentId: 'USR-82015',
    name: 'Naveen Chandra',
    avatarUrl: '/assets/avatar_test2.png',
    location: 'VIZAG, MVP COLONY',
    dateTime: '7th Oct – 09:40 AM',
    totalCredits: 350,
    creditsUsed: 120,
    creditsRemaining: 230,
    cashEarned: 90000,
    formattedCashEarned: '₹90,000.00',
    phone: '+91 97003 44556',
    email: 'naveen.chandra@gmail.com',
    role: 'Agri-Pool Member',
    status: 'Authorized',
    entityType: 'User',
    recentTransactions: [
      {
        id: 'tx-u3',
        date: '07 Oct 2026, 09:30 AM',
        landId: 'GLC VZG 09',
        type: 'Credit Consumption',
        credits: 120,
        cashEquivalent: '₹90,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'usr-4',
    agentId: 'USR-55219',
    name: 'Kavitha Reddy',
    avatarUrl: '/assets/avatar_test3.png',
    location: 'VIJAYAWADA, BENZ CIRCLE',
    dateTime: '8th Oct – 04:10 PM',
    totalCredits: 800,
    creditsUsed: 300,
    creditsRemaining: 500,
    cashEarned: 250000,
    formattedCashEarned: '₹2,50,000.00',
    phone: '+91 98850 11992',
    email: 'kavitha.reddy@reddyinfra.com',
    role: 'Institutional Buyer',
    status: 'Authorized',
    entityType: 'User',
    recentTransactions: [
      {
        id: 'tx-u4',
        date: '08 Oct 2026, 04:00 PM',
        landId: 'GLC VJA 03',
        type: 'Credit Consumption',
        credits: 300,
        cashEquivalent: '₹2,50,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'usr-5',
    agentId: 'USR-71642',
    name: 'Deepak Nair',
    avatarUrl: '/assets/lead-1.png',
    location: 'WARANGAL, KAZIPET',
    dateTime: '9th Oct – 01:25 PM',
    totalCredits: 300,
    creditsUsed: 80,
    creditsRemaining: 220,
    cashEarned: 60000,
    formattedCashEarned: '₹60,000.00',
    phone: '+91 94412 88334',
    email: 'deepak.nair@nairagri.in',
    role: 'Farmland Owner',
    status: 'Pending',
    entityType: 'User',
    recentTransactions: [
      {
        id: 'tx-u5',
        date: '09 Oct 2026, 01:00 PM',
        landId: 'GLC TNK 02',
        type: 'Credit Consumption',
        credits: 80,
        cashEquivalent: '₹60,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'usr-6',
    agentId: 'USR-63028',
    name: 'Priya Sharma',
    avatarUrl: '/assets/lead-2.png',
    location: 'GUNTUR, BRODIPET',
    dateTime: '10th Oct – 10:50 AM',
    totalCredits: 450,
    creditsUsed: 150,
    creditsRemaining: 300,
    cashEarned: 100000,
    formattedCashEarned: '₹1,00,000.00',
    phone: '+91 98765 12098',
    email: 'priya.sharma@sharmaconsult.com',
    role: 'Verified Subscriber',
    status: 'Authorized',
    entityType: 'User',
    recentTransactions: [
      {
        id: 'tx-u6',
        date: '10 Oct 2026, 10:30 AM',
        landId: 'GLC GNT 11',
        type: 'Credit Consumption',
        credits: 150,
        cashEquivalent: '₹1,00,000.00',
        status: 'Completed',
      },
    ],
  },
  {
    id: 'usr-7',
    agentId: 'USR-82190',
    name: 'Anil Kumar',
    avatarUrl: '/assets/agent-1.png',
    location: 'HYDERABAD, MADHAPUR',
    dateTime: '11th Oct – 02:40 PM',
    totalCredits: 500,
    creditsUsed: 140,
    creditsRemaining: 360,
    cashEarned: 90000,
    formattedCashEarned: '₹90,000.00',
    phone: '+91 98480 33412',
    email: 'anil.k@kumarfarms.in',
    role: 'Growth Plan Subscriber',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-8',
    agentId: 'USR-73201',
    name: 'Radhika Sen',
    avatarUrl: '/assets/agent-2.png',
    location: 'BENGALURU, INDIRANAGAR',
    dateTime: '11th Oct – 05:15 PM',
    totalCredits: 350,
    creditsUsed: 95,
    creditsRemaining: 255,
    cashEarned: 62000,
    formattedCashEarned: '₹62,000.00',
    phone: '+91 99011 88321',
    email: 'radhika.sen@sentrust.org',
    role: 'Farmland Investor',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-9',
    agentId: 'USR-61942',
    name: 'Gautam Singhania',
    avatarUrl: '/assets/agent-3.png',
    location: 'MUMBAI, BANDRA',
    dateTime: '12th Oct – 11:00 AM',
    totalCredits: 700,
    creditsUsed: 220,
    creditsRemaining: 480,
    cashEarned: 150000,
    formattedCashEarned: '₹1,50,000.00',
    phone: '+91 98200 44102',
    email: 'gautam.s@singhaniaholdings.com',
    role: 'Platinum Farmland Investor',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-10',
    agentId: 'USR-50491',
    name: 'Swati Deshmukh',
    avatarUrl: '/assets/agent-4.png',
    location: 'PUNE, KOTHRUD',
    dateTime: '12th Oct – 03:30 PM',
    totalCredits: 420,
    creditsUsed: 110,
    creditsRemaining: 310,
    cashEarned: 76000,
    formattedCashEarned: '₹76,000.00',
    phone: '+91 98221 66490',
    email: 'swati.d@deshmukhestate.in',
    role: 'Verified Subscriber',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-11',
    agentId: 'USR-48102',
    name: 'K. V. Subbarao',
    avatarUrl: '/assets/agent-5.png',
    location: 'VIJAYAWADA, BENZ CIRCLE',
    dateTime: '13th Oct – 10:20 AM',
    totalCredits: 480,
    creditsUsed: 130,
    creditsRemaining: 350,
    cashEarned: 85000,
    formattedCashEarned: '₹85,000.00',
    phone: '+91 98491 22091',
    email: 'kv.subbarao@andhrafarms.in',
    role: 'Farmland Owner',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-12',
    agentId: 'USR-39201',
    name: 'Nandini Joshi',
    avatarUrl: '/assets/agent-6.png',
    location: 'HYDERABAD, JUBILEE HILLS',
    dateTime: '13th Oct – 01:45 PM',
    totalCredits: 550,
    creditsUsed: 160,
    creditsRemaining: 390,
    cashEarned: 110000,
    formattedCashEarned: '₹1,10,000.00',
    phone: '+91 98499 88120',
    email: 'nandini.j@joshiventures.com',
    role: 'Platinum Farmland Investor',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-13',
    agentId: 'USR-29104',
    name: 'Vikramaditya Bose',
    avatarUrl: '/assets/avatar.png',
    location: 'KOLKATA, ALIPORE',
    dateTime: '14th Oct – 09:50 AM',
    totalCredits: 380,
    creditsUsed: 90,
    creditsRemaining: 290,
    cashEarned: 68000,
    formattedCashEarned: '₹68,000.00',
    phone: '+91 98301 55421',
    email: 'vikram.bose@boseenterprises.in',
    role: 'Growth Plan Subscriber',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-14',
    agentId: 'USR-18290',
    name: 'Tanya Mehra',
    avatarUrl: '/assets/avatar_test1.png',
    location: 'DELHI, VASANT VIHAR',
    dateTime: '14th Oct – 12:15 PM',
    totalCredits: 620,
    creditsUsed: 190,
    creditsRemaining: 430,
    cashEarned: 130000,
    formattedCashEarned: '₹1,30,000.00',
    phone: '+91 98110 33490',
    email: 'tanya.mehra@mehracorp.com',
    role: 'Platinum Farmland Investor',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-15',
    agentId: 'USR-84729',
    name: 'Raghavan Iyer',
    avatarUrl: '/assets/avatar_test2.png',
    location: 'CHENNAI, ADYAR',
    dateTime: '14th Oct – 03:00 PM',
    totalCredits: 440,
    creditsUsed: 120,
    creditsRemaining: 320,
    cashEarned: 80000,
    formattedCashEarned: '₹80,000.00',
    phone: '+91 98400 77123',
    email: 'raghavan.i@iyerproperties.in',
    role: 'Verified Subscriber',
    status: 'Authorized',
    entityType: 'User',
  },
  {
    id: 'usr-16',
    agentId: 'USR-95810',
    name: 'Snehlata Bajaj',
    avatarUrl: '/assets/avatar_test3.png',
    location: 'AHMEDABAD, SATELLITE',
    dateTime: '14th Oct – 05:40 PM',
    totalCredits: 490,
    creditsUsed: 135,
    creditsRemaining: 355,
    cashEarned: 92000,
    formattedCashEarned: '₹92,000.00',
    phone: '+91 98250 11984',
    email: 'snehlata.b@bajajagro.in',
    role: 'Growth Plan Subscriber',
    status: 'Authorized',
    entityType: 'User',
  },
];
